stages:
  preprocess:
    cmd: poetry run python run_preprocess.py
    deps:
      - data/raw/online_shoppers_intention.csv
      - src/ecommerce_buy_predictor/data/loader.py
      - src/ecommerce_buy_predictor/data/preprocess.py
      - run_preprocess.py
    outs:
      - data/processed:
          cache: true

  train:
    cmd: poetry run python run_train.py
    deps:
      - data/processed
      - src/ecommerce_buy_predictor/models/train.py
      - src/ecommerce_buy_predictor/models/evaluate.py
      - params.yaml
      - run_train.py
    outs:
      - models/model.pkl

  evaluate:
    cmd: poetry run python run_evaluate.py
    deps:
      - src/ecommerce_buy_predictor/models/registry.py
      - models/model.pkl
      - run_evaluate.py
    metrics:
      - metrics.json:
          cache: false
